openapi: 3.0.3
info : 
  title : STD24011
  description: This is a specification of STD24011
  version: 1.0.0
servers:
  - url: http://localhost:8000

paths:
  /booking:
    get: 
      description: return the lists of reservations
      responses : 
        '200' : 
          description: These are the lists of reservations
          content:
            application/json :
              schema : 
                type: array
                items : 
                  $ref : '#/components/schemas/Reservations'
    post : 
      description : add a new reservation
      requestBody :
        content:
          application/json:
            schema :
              items :
                $ref : '#/components/schemas/Reservations'
        
      responses:
        '201' :
          description: Reservation added
          content:
            application/json :
              schema :
                items :
                  $ref : '#/components/schemas/Reservations'
                  

      

                  
                    
            

components:
  schemas:
    Reservations:
      required:
        - name
        - phone_Number
        - email
        - room_number
        - room_description
        - reservation_date
      items : 
        type : object
      
